# Generated by Django 2.2.15 on 2020-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20200806_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
