# Generated by Django 2.2.15 on 2020-08-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20200806_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuser',
            name='is_confirmed',
        ),
    ]
