# Generated by Django 2.2.15 on 2020-08-12 10:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_remove_applicationuser_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicationuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
