# Generated by Django 2.2.16 on 2020-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200915_0723'),
        ('custom_auth', '0005_auto_20200812_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='countries_available',
            field=models.ManyToManyField(blank=True, help_text='The countries with which the user is associated to create permissions.', related_name='countries_available', to='locations.Country', verbose_name='countries_available'),
        ),
    ]
