# Generated by Django 2.2.15 on 2020-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='countrydailystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_availability',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_status',
            field=models.CharField(default='unknown', max_length=64),
        ),
    ]
