# Generated by Django 2.2.15 on 2020-08-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0002_auto_20200813_0948'),
        ('connection_statistics', '0002_auto_20200817_0902'),
    ]

    operations = [
    ]
