# Generated by Django 2.2.15 on 2020-08-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0005_auto_20200821_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydailystatus',
            options={'ordering': ('id',), 'verbose_name': 'Country Daily Connectivity Summary', 'verbose_name_plural': 'Country Daily Connectivity Summary'},
        ),
        migrations.AlterModelOptions(
            name='realtimeconnectivity',
            options={'ordering': ('id',), 'verbose_name': 'Real Time Connectivity Data', 'verbose_name_plural': 'Real Time Connectivity Data'},
        ),
        migrations.AlterModelOptions(
            name='schooldailystatus',
            options={'ordering': ('id',), 'verbose_name': 'School Daily Connectivity Summary', 'verbose_name_plural': 'School Daily Connectivity Summary'},
        ),
        migrations.AlterModelOptions(
            name='schoolweeklystatus',
            options={'ordering': ('id',), 'verbose_name': 'School Summary', 'verbose_name_plural': 'School Summary'},
        ),
    ]
