# Generated by Django 2.2.15 on 2020-09-03 07:43

import datetime
from django.db import migrations, models


def clean_old_data(apps, schema_editor):
    CountryDailyStatus = apps.get_model('connection_statistics', 'CountryDailyStatus')
    SchoolDailyStatus = apps.get_model('connection_statistics', 'SchoolDailyStatus')
    CountryDailyStatus.objects.all().delete()
    SchoolDailyStatus.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('connection_statistics', '0007_auto_20200827_0627'),
    ]

    operations = [
        migrations.RunPython(clean_old_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='countrydailystatus',
            name='week',
        ),
        migrations.RemoveField(
            model_name='countrydailystatus',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='countrydailystatus',
            name='year',
        ),
        migrations.RemoveField(
            model_name='schooldailystatus',
            name='week',
        ),
        migrations.RemoveField(
            model_name='schooldailystatus',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='schooldailystatus',
            name='year',
        ),
        migrations.AddField(
            model_name='countrydailystatus',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 3)),
            preserve_default=False,
        ),
    ]
