# Generated by Django 2.2.16 on 2020-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0010_auto_20200909_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_status',
            field=models.CharField(choices=[('unknown', 'Data unavailable'), ('no', 'No connectivity'), ('moderate', 'Moderate'), ('good', 'Good')], default='unknown', max_length=8),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Latency (ms)'),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Down speed (mbps)'),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_type',
            field=models.CharField(default='unknown', max_length=64, verbose_name='Type of internet connection'),
        ),
    ]
