# Generated by Django 2.2.16 on 2020-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0011_auto_20200909_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity',
            field=models.BooleanField(default=False),
        ),
    ]
