# Generated by Django 2.2.16 on 2020-09-11 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0013_auto_20200909_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
