# Generated by Django 2.2.16 on 2020-09-11 10:13

from django.db import migrations


def set_initial_weekly_status(apps, schema_migration):
    Country = apps.get_model('locations', 'Country')
    CountryWeeklyStatus = apps.get_model('connection_statistics', 'CountryWeeklyStatus')
    School = apps.get_model('schools', 'School')

    for country in Country.objects.all():
        qs = CountryWeeklyStatus.objects.filter(country=country)
        if not qs.exists():
            integration_status = 1 if School.objects.filter(country=country, geopoint__isnull=False).exists() else 0
            CountryWeeklyStatus.objects.create(country=country, integration_status=integration_status)


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0014_auto_20200911_1012'),
        ('locations', '0004_auto_20200822_0919'),
        ('schools', '0007_auto_20200817_1104'),
    ]

    operations = [
        migrations.RunPython(set_initial_weekly_status)
    ]
