# Generated by Django 2.2.16 on 2020-09-15 07:40

from django.db import migrations, models


def change_country_weekly_empty_values_in_models(apps, schema_editor):
    CountryWeeklyStatus = apps.get_model("connection_statistics", "CountryWeeklyStatus")

    for country_weekly in CountryWeeklyStatus.objects.all():
        if not country_weekly.schools_total:
            country_weekly.schools_total = 0
        if not country_weekly.schools_connected:
            country_weekly.schools_connected = 0
        if not country_weekly.schools_connectivity_unknown:
            country_weekly.schools_connectivity_unknown = 0
        if not country_weekly.schools_connectivity_no:
            country_weekly.schools_connectivity_no = 0
        if not country_weekly.schools_connectivity_moderate:
            country_weekly.schools_connectivity_moderate = 0
        if not country_weekly.schools_connectivity_good:
            country_weekly.schools_connectivity_good = 0
        if not country_weekly.connectivity_speed:
            country_weekly.connectivity_speed = 0.0
        if not country_weekly.avg_distance_school:
            country_weekly.avg_distance_school = 0.0

        country_weekly.save()


def change_school_weekly_empty_values_in_models(apps, schema_editor):
    SchoolWeeklyStatus = apps.get_model("connection_statistics", "SchoolWeeklyStatus")

    for school_weekly in SchoolWeeklyStatus.objects.all():
        if not school_weekly.num_students:
            school_weekly.num_students = 0
        if not school_weekly.num_teachers:
            school_weekly.num_teachers = 0
        if not school_weekly.num_classroom:
            school_weekly.num_classroom = 0
        if not school_weekly.num_latrines:
            school_weekly.num_latrines = 0
        if not school_weekly.num_computers:
            school_weekly.num_computers = 0
        if not school_weekly.connectivity_speed:
            school_weekly.connectivity_speed = 0.0
        if not school_weekly.connectivity_latency:
            school_weekly.connectivity_latency = 0
        if not school_weekly.connectivity_availability:
            school_weekly.connectivity_availability = 0.0

        school_weekly.save()


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0015_auto_20200911_1013'),
    ]

    operations = [
        migrations.RunPython(change_country_weekly_empty_values_in_models, migrations.RunPython.noop),
        migrations.RunPython(change_school_weekly_empty_values_in_models, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='avg_distance_school',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_connected',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_connectivity_good',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_connectivity_moderate',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_connectivity_no',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_connectivity_unknown',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='schools_total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_availability',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Latency (ms)'),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Down speed (mbps)'),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_classroom',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_computers',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_latrines',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_students',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='num_teachers',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
