# Generated by Django 2.2.16 on 2020-09-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200822_0919'),
        ('schools', '0007_auto_20200817_1104'),
        ('connection_statistics', '0015_auto_20200911_1013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrydailystatus',
            unique_together={('date', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='countryweeklystatus',
            unique_together={('year', 'week', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='schooldailystatus',
            unique_together={('date', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolweeklystatus',
            unique_together={('year', 'week', 'school')},
        ),
    ]
