# Generated by Django 2.2.16 on 2020-09-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0016_auto_20200914_1631'),
        ('connection_statistics', '0016_auto_20200915_0740'),
    ]

    operations = [
    ]
