# Generated by Django 2.2.16 on 2020-09-23 12:18

from django.db import migrations


def delete_empty_entries(apps, schema_editor):
    RealTimeConnectivity = apps.get_model('connection_statistics', 'RealTimeConnectivity')

    RealTimeConnectivity.objects.filter(connectivity_speed__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0019_auto_20200922_0924'),
    ]

    operations = [
        migrations.RunPython(delete_empty_entries, migrations.RunPython.noop),
    ]
