# Generated by Django 2.2.16 on 2020-09-28 13:17

from django.db import migrations, models



def migrate_speed_field(apps, schema_editor):
    CountryWeeklyStatus = apps.get_model("connection_statistics", "CountryWeeklyStatus")
    SchoolWeeklyStatus = apps.get_model("connection_statistics", "SchoolWeeklyStatus")
    CountryDailyStatus = apps.get_model("connection_statistics", "CountryDailyStatus")
    SchoolDailyStatus = apps.get_model("connection_statistics", "SchoolDailyStatus")
    RealTimeConnectivity = apps.get_model("connection_statistics", "RealTimeConnectivity")

    models_list = [
        CountryWeeklyStatus, SchoolWeeklyStatus, CountryDailyStatus, SchoolDailyStatus, RealTimeConnectivity,
    ]

    for model in models_list:
        model.objects.update(connectivity_speed_in_bits=models.F('connectivity_speed') * (10 ** 6))


def reverse_speed_field(apps, schema_editor):
    CountryWeeklyStatus = apps.get_model("connection_statistics", "CountryWeeklyStatus")
    SchoolWeeklyStatus = apps.get_model("connection_statistics", "SchoolWeeklyStatus")
    CountryDailyStatus = apps.get_model("connection_statistics", "CountryDailyStatus")
    SchoolDailyStatus = apps.get_model("connection_statistics", "SchoolDailyStatus")
    RealTimeConnectivity = apps.get_model("connection_statistics", "RealTimeConnectivity")

    models_list = [
        CountryWeeklyStatus, SchoolWeeklyStatus, CountryDailyStatus, SchoolDailyStatus, RealTimeConnectivity,
    ]

    for model in models_list:
        model.objects.update(connectivity_speed=1.0 * models.F('connectivity_speed_in_bits') / (10 ** 6))


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0020_auto_20200923_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydailystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='realtimeconnectivity',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schooldailystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='connectivity_speed_in_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_speed_field, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='countrydailystatus',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='countryweeklystatus',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='realtimeconnectivity',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='schooldailystatus',
            name='connectivity_speed',
        ),
        migrations.RemoveField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='countrydailystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='countryweeklystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='realtimeconnectivity',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='schooldailystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
        migrations.RenameField(
            model_name='schoolweeklystatus',
            old_name='connectivity_speed_in_bits',
            new_name='connectivity_speed',
        ),
    ]
