# Generated by Django 2.2.16 on 2020-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0023_auto_20200930_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailystatus',
            name='connectivity_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='countryweeklystatus',
            name='connectivity_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='connectivity_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='connectivity_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_speed',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='bps', null=True),
        ),
    ]
