# Generated by Django 2.2.16 on 2020-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0024_auto_20200930_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='countrydailystatus',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='realtimeconnectivity',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='schooldailystatus',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_latency',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='ms', null=True),
        ),
    ]
