# Generated by Django 2.2.16 on 2020-10-07 08:49

from django.db import migrations
from django.db.models import Avg, Q


def fix_country_weekly_status_speed_calculations(apps, schema_editor):
    SchoolWeeklyStatus = apps.get_model('connection_statistics', 'SchoolWeeklyStatus')
    CountryWeeklyStatus = apps.get_model('connection_statistics', 'CountryWeeklyStatus')

    for country_status in CountryWeeklyStatus.objects.all():
        schools_stats = SchoolWeeklyStatus.objects.filter(
            year=country_status.year, week=country_status.week, school__country=country_status.country,
        ).aggregate(
            connectivity_speed=Avg('connectivity_speed', filter=Q(connectivity_speed__gt=0)),
            connectivity_latency=Avg('connectivity_latency', filter=Q(connectivity_latency__gt=0)),
        )
        country_status.connectivity_speed = schools_stats['connectivity_speed'] or 0
        country_status.connectivity_latency = schools_stats['connectivity_latency'] or 0
        country_status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0026_auto_20200930_1033'),
    ]

    operations = [
        migrations.RunPython(fix_country_weekly_status_speed_calculations, migrations.RunPython.noop),
    ]
