# Generated by Django 2.2.16 on 2020-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0029_auto_20201020_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity',
            field=models.NullBooleanField(default=None),
        ),
    ]
