# Generated by Django 2.2.15 on 2020-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0030_auto_20201022_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolweeklystatus',
            name='connectivity_availability',
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='coverage_availability',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='schoolweeklystatus',
            name='coverage_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('no', 'No'), ('2g', '2G'), ('3g', '3G'), ('4g', '4G')], default='unknown', max_length=8),
        ),
    ]
