# Generated by Django 2.2.15 on 2020-10-27 11:57

from django.db import migrations


def set_coverage_statuses(apps, schema_editor):
    SchoolWeeklyStatus = apps.get_model('connection_statistics', 'SchoolWeeklyStatus')

    base_sw_qs = SchoolWeeklyStatus.objects.exclude(connectivity_type='unknown')
    base_sw_qs.update(coverage_availability=True)
    base_sw_qs.filter(connectivity_type__iregex=r'.*2g.*').update(coverage_availability=True, coverage_type='2g')
    base_sw_qs.filter(connectivity_type__iregex=r'.*3g.*').update(coverage_availability=True, coverage_type='4g')
    base_sw_qs.filter(connectivity_type__iregex=r'.*4g.*').update(coverage_availability=True, coverage_type='3g')
    base_sw_qs.filter(connectivity_type__iexact='no covered').update(coverage_availability=False, coverage_type='no')
    base_sw_qs.filter(connectivity_type__iexact='no').update(coverage_availability=False, coverage_type='no')
    base_sw_qs.filter(connectivity_type__iexact='no service').update(coverage_availability=False, coverage_type='no')


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0031_auto_20201027_1150'),
    ]

    operations = [
        migrations.RunPython(set_coverage_statuses, migrations.RunPython.noop),
    ]
