# Generated by Django 2.2.16 on 2020-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0032_auto_20201027_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolweeklystatus',
            name='connectivity_status',
            field=models.CharField(choices=[('no', 'No connectivity'), ('unknown', 'Data unavailable'), ('moderate', 'Moderate'), ('good', 'Good')], db_index=True, default='unknown', max_length=8),
        ),
    ]
