# Generated by Django 2.2.16 on 2020-11-02 13:18

from django.db import migrations
from isoweek import Week


def fix_weekly_date(apps, schema_editor):
    CountryWeeklyStatus = apps.get_model('connection_statistics', 'CountryWeeklyStatus')
    SchoolWeeklyStatus = apps.get_model('connection_statistics', 'SchoolWeeklyStatus')

    for s in SchoolWeeklyStatus.objects.all():
        s.date = Week(s.year, s.week).monday()
        s.save()

    for s in CountryWeeklyStatus.objects.all():
        s.date = Week(s.year, s.week).monday()
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0033_auto_20201030_0707'),
    ]

    operations = [
        migrations.RunPython(fix_weekly_date, migrations.RunPython.noop),
    ]
