# Generated by Django 2.2.15 on 2020-11-19 19:42

from django.db import migrations, models


def set_countries_connectivity_and_coverage_availability(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')
    SchoolWeeklyStatus = apps.get_model('connection_statistics', 'SchoolWeeklyStatus')

    for country in Country.objects.all():
        # connectivity
        if SchoolWeeklyStatus.objects.filter(
            school__country=country,
            connectivity_speed__isnull=False,
        ).exists():
            country.last_weekly_status.connectivity_availability = 2

        elif SchoolWeeklyStatus.objects.filter(
            school__country=country,
            connectivity__in=[True, False],
        ).exists():
            country.last_weekly_status.connectivity_availability = 1

        else:
            continue

        # coverage
        if SchoolWeeklyStatus.objects.filter(
            school__country=country,
            coverage_type__in=['no', '2g', '3g', '4g'],
        ).exists():
            country.last_weekly_status.coverage_availability = 2

        elif SchoolWeeklyStatus.objects.filter(
            school__country=country,
            coverage_availability__in=[True, False],
        ).exists():
            country.last_weekly_status.coverage_availability = 1

        else:
            continue

        country.last_weekly_status.save(update_fields=['connectivity_availability', 'coverage_availability'])


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0034_auto_20201102_1318'),
        ('locations', '0009_country_last_weekly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_availability',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No data'), (1, 'Using availability information'), (2, 'Using actual speeds')], default=0),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='coverage_availability',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No data'), (1, 'Using availability information'), (2, 'Using actual speeds')], default=0),
        ),
        migrations.RunPython(set_countries_connectivity_and_coverage_availability, migrations.RunPython.noop)
    ]
