# Generated by Django 2.2.15 on 2020-11-20 11:39

from django.db import migrations, models


def set_countries_connectivity_and_coverage_availability(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')
    SchoolWeeklyStatus = apps.get_model('connection_statistics', 'SchoolWeeklyStatus')

    for country in Country.objects.all():
        # connectivity
        if SchoolWeeklyStatus.objects.filter(
            school__country=country,
            connectivity_speed__isnull=False,
        ).exists():
            country.last_weekly_status.connectivity_availability = 'static_speed'
            if country.daily_status.exists():
                country.last_weekly_status.connectivity_availability = 'realtime_speed'

        elif SchoolWeeklyStatus.objects.filter(
            school__country=country,
            connectivity__in=[True, False],
        ).exists():
            country.last_weekly_status.connectivity_availability = 'connectivity'

        else:
            continue

        # coverage
        if SchoolWeeklyStatus.objects.filter(
            school__country=country,
            coverage_type__in=['no', '2g', '3g', '4g'],
        ).exists():
            country.last_weekly_status.coverage_availability = 'coverage_type'

        elif SchoolWeeklyStatus.objects.filter(
            school__country=country,
            coverage_availability__in=[True, False],
        ).exists():
            country.last_weekly_status.coverage_availability = 'coverage_availability'

        else:
            continue

        country.last_weekly_status.save(update_fields=['connectivity_availability', 'coverage_availability'])


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0037_auto_20201120_1108'),
        ('locations', '0009_country_last_weekly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='connectivity_availability',
            field=models.CharField(choices=[('no_connectivity', 'No data'), ('connectivity', 'Using availability information'), ('static_speed', 'Using actual static speeds'), ('realtime_speed', 'Using actual realtime speeds')], default='no_connectivity', max_length=32),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='coverage_availability',
            field=models.CharField(choices=[('no_coverage', 'No data'), ('coverage_availability', 'Using availability information'), ('coverage_type', 'Using actual coverage type')], default='no_coverage', max_length=32),
        ),
        migrations.RunPython(set_countries_connectivity_and_coverage_availability, migrations.RunPython.noop)
    ]
