# Generated by Django 2.2.16 on 2020-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0038_auto_20201120_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryweeklystatus',
            name='schools_coverage_good',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='schools_coverage_moderate',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='schools_coverage_no',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='countryweeklystatus',
            name='schools_coverage_unknown',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
