# Generated by Django 2.2.18 on 2021-03-24 13:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckApp_Measurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField()),
                ('UUID', models.TextField(blank=True)),
                ('BrowserID', models.TextField(blank=True)),
                ('school_id', models.TextField()),
                ('DeviceType', models.TextField(blank=True)),
                ('Notes', models.TextField()),
                ('ClientInfo', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ServerInfo', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('annotation', models.TextField(blank=True)),
                ('Download', models.FloatField(blank=True)),
                ('Upload', models.FloatField(blank=True)),
                ('Latency', models.IntegerField(blank=True)),
                ('Results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'dailycheckapp_measurements',
                'managed': False,
            },
        ),
    ]
