# Generated by Django 2.2.15 on 2020-08-06 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('geopoint', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('gps_confidence', models.DecimalField(decimal_places=5, max_digits=5)),
                ('altitude', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True)),
                ('education_level', models.CharField(choices=[('preschool', 'Early childhood education'), ('primary', 'Primary education'), ('secondary', 'Secondary education')], default='preschool', max_length=64)),
                ('environment', models.CharField(choices=[('urban', 'Urban'), ('semi_rural', 'Semi-rural'), ('rural', 'Rural')], default='urban', max_length=64)),
                ('school_type', models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('religious', 'Religious')], default='private', max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='locations.Country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='locations.Location')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
