# Generated by Django 2.2.15 on 2020-08-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_fileimport_errors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileimport',
            options={'ordering': ('id',)},
        ),
    ]
