# Generated by Django 2.2.16 on 2020-09-15 07:54

from django.db import migrations, models


def change_empty_values_in_models(apps, schema_editor):
    School = apps.get_model("schools", "School")

    for school in School.objects.all():
        if not school.altitude:
            school.altitude = 0
            school.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20200817_1104'),
    ]

    operations = [
        migrations.RunPython(change_empty_values_in_models, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='school',
            name='altitude',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
