# Generated by Django 2.2.16 on 2020-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20200915_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='environment',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban')], max_length=64),
        ),
    ]
