# Generated by Django 2.2.16 on 2020-10-21 10:52

from django.db import migrations, models
import django.db.models.deletion


def set_last_status(apps, schema_editor):
    School = apps.get_model("schools", "School")
    SchoolWeeklyStatus = apps.get_model("connection_statistics", "SchoolWeeklyStatus")

    School.objects.annotate(
        last_status_id=models.Subquery(
            SchoolWeeklyStatus.objects.filter(
                school=models.OuterRef('id'),
            ).order_by('-year', '-week', '-id')[:1].values('id'),
        ),
    ).update(last_weekly_status_id=models.F('last_status_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0029_auto_20201020_1143'),
        ('schools', '0010_auto_20201013_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_weekly_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_school', to='connection_statistics.SchoolWeeklyStatus'),
        ),
        migrations.RunPython(set_last_status, migrations.RunPython.noop),
    ]
