# Generated by Django 2.2.16 on 2020-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20201023_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('completed_with_errors', 'Completed with errors')], default='pending', max_length=21),
        ),
    ]
