# Generated by Django 2.2.16 on 2020-10-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_country_last_weekly_status'),
        ('schools', '0013_auto_20201028_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Country'),
        ),
    ]
