# Generated by Django 2.2.16 on 2020-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_fileimport_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name_lower',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
