# Generated by Django 2.2.16 on 2020-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20201103_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name_lower',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
