# Generated by Django 2.2.17 on 2020-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_auto_20201117_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='statistic',
            field=models.TextField(blank=True),
        ),
    ]
