# Generated by Django 2.2.18 on 2021-04-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_fileimport_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='last_weekly_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_school', to='connection_statistics.SchoolWeeklyStatus'),
        ),
    ]
