# Generated by Django 2.2.15 on 2020-08-17 10:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200817_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='geometry_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Simplified Geometry'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Country border geometry'),
        ),
    ]
