# Generated by Django 2.2.16 on 2020-09-15 07:23

from django.db import migrations, models


def change_empty_values_in_models(apps, schema_editor):
    Country = apps.get_model("locations", "Country")

    for country in Country.objects.all():
        if not country.description:
            country.description = ''
        if not country.data_source:
            country.data_source = ''
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200822_0919'),
    ]

    operations = [
        migrations.RunPython(change_empty_values_in_models, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='country',
            name='data_source',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
