# Generated by Django 2.2.16 on 2020-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_country_date_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='date_schools_mapped',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
