# Generated by Django 2.2.16 on 2020-10-19 07:35

from django.db import migrations


def set_date_schools_mapped(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')
    CountryWeeklyStatus = apps.get_model('connection_statistics', 'CountryWeeklyStatus')

    for country in Country.objects.all():
        weekly_statuses = CountryWeeklyStatus.objects.filter(country=country, integration_status__in=[1, 2, 3])
        if weekly_statuses.exists():
            date = weekly_statuses.first().date
            country.date_schools_mapped = date
            country.save(update_fields=('date_schools_mapped',))


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_country_date_schools_mapped'),
        ('connection_statistics', '0028_auto_20201012_1128'),
    ]

    operations = [
        migrations.RunPython(set_date_schools_mapped, migrations.RunPython.noop),
    ]
