# Generated by Django 2.2.15 on 2020-10-22 09:31

from django.db import migrations, models
import django.db.models.deletion


def set_last_weekly_status(apps, schema_editor):
    CountryWeeklyStatus = apps.get_model('connection_statistics', 'CountryWeeklyStatus')
    Country = apps.get_model('locations', 'Country')

    Country.objects.annotate(
        last_status_id=models.Subquery(
            CountryWeeklyStatus.objects.filter(
                country=models.OuterRef('id'),
            ).order_by('-year', '-week', '-id')[:1].values('id'),
        ),
    ).update(last_weekly_status_id=models.F('last_status_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('connection_statistics', '0029_auto_20201020_1143'),
        ('locations', '0008_auto_20201019_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='last_weekly_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_country', to='connection_statistics.CountryWeeklyStatus'),
        ),
        migrations.RunPython(set_last_weekly_status, migrations.RunPython.noop)
    ]
