# Generated by Django 2.2.15 on 2020-11-20 14:07

from django.db import migrations


def capitalize_data_source(apps, schema_editor):
    Country = apps.get_model('locations', 'Country')

    for country in Country.objects.all():
        if country.data_source:
            for idx in range(len(list_ := country.data_source.split('\n'))):
                list_[idx] = list_[idx].capitalize()
            country.data_source = '\n'.join(list_)
            country.save(update_fields=('data_source',))


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_country_last_weekly_status'),
    ]

    operations = [
        migrations.RunPython(capitalize_data_source, migrations.RunPython.noop)
    ]
