# Generated by Django 2.2.18 on 2021-04-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201120_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date_of_join',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='last_weekly_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_country', to='connection_statistics.CountryWeeklyStatus'),
        ),
    ]
