# Generated by Django 2.2.18 on 2021-03-24 13:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('uuid', models.TextField(blank=True)),
                ('browser_id', models.TextField(blank=True)),
                ('school_id', models.TextField()),
                ('device_type', models.TextField(blank=True)),
                ('notes', models.TextField()),
                ('client_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('server_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('annotation', models.TextField(blank=True)),
                ('download', models.FloatField(blank=True)),
                ('upload', models.FloatField(blank=True)),
                ('latency', models.IntegerField(blank=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'measurements',
                'managed': False,
            },
        ),
    ]
